version: "3.8"
services:
  angular:
    build: .
    ports:
      - "4000:4200"
    volumes:
      - "/app/node_modules"
      - ".:/app"
    networks:
      - ems-network

networks:
    ems-network:
      external: true
